CREATE DATABASE BubbleDog;
SHOW DATABASES ;
# Conectarse a BD
USE BubbleDog;

CREATE TABLE IF NOT EXISTS cliente(
	cedula VARCHAR(20) NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    nombre_mascota VARCHAR(20) NOT NULL,
    raza VARCHAR(20) NOT NULL,
    vacunas BOOLEAN NOT NULL, #en BD sale cero si es false y 1 si es true
    observacion TEXT NOT NULL,
    #hora_entrega DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (cedula)
);

INSERT INTO cliente(cedula,nombre,apellido,telefono,email,nombre_mascota,raza,vacunas,observacion)
VALUES('123456789','PEPITO','PEREZ','8000','...@GMIAL.COM','NEGRO','CRIOLLO',FALSE,'ESTA GORDO');

SELECT * FROM cliente;
TRUNCATE TABLE cliente;
DROP TABLE cliente; 

CREATE TABLE IF NOT EXISTS servicio(
	id_servicio INT AUTO_INCREMENT NOT NULL,
    nombre_servicio TEXT NOT NULL,
    costo_servicio INT NOT NULL,
    detalles_servicio TEXT NOT NULL,
    PRIMARY KEY (id_servicio)
);

INSERT INTO servicio(nombre_servicio,costo_servicio,detalles_servicio)
VALUES
	('BAÑO',25000,'EL BAÑO SE HACE ABUNDANTE AGUA Y SHAMPOO ESPECIAL PARA MASCONTAS Y ASI EVITAR IRRITACIONES EN LA PIEL DEL ANIMAL'),
    ('DESLANADO',10000,'EL DESLANADO CONSISTE EN CEPILLAR MUY BIEN LA MASCOTA PARA RETIRAR TODO EL PELO MUERTO QUE PUDIERA QUEDAR TRAS EL BAÑO'),
    ('CORTE DE UÑAS',5000,'MANTENER LAS UÑAS DE NUETRA MASCOTA CORTAS ES ESENCIL PARA NUETRAS MASCOTA ESTE SALUDABLE'),
    ('CEPILLADO DE DIENTES',12000,'PREVIENE EL MAL ALIENTO DE NUENTRA MASCOTA, PERO ES RECOMENDARBLE HACERLO CON REGULARIDAD (ES UN TRATAMIENDO DIFERENTE A LA PROFILAXIS)'),
    ('DRENADO DE GLANDULAS PERIANALES',15000,'REALIZAR ESTE PROCEDIMIENTO CON REGULARIDAD ES FUNDAMENTAL PARA PREVENIR ENFERMEDADES INFECCIOSAS EN NUETRA MASCOTA'),
    ('PELUQUEADO',30000,'NUESTRO ESTILISTA EXPERTO SE ENCARGARA DE HACER UN CORTE DE PELO IDEAL PARA TU MASCOTA TENIENDO EN CUENTO SU TAMAÑO, RAZA Y TIPO DE PELO'),
    ('COMBO B.D.C',35000,'BAÑO, DESLANADO Y CORTE DE UÑAS'),
    ('COMBO B.D.C.D.C',60000,'BAÑO, DESLANADO, CORTE DE UÑAS, DRENADO DE GLANDULAS Y CEPILLADO DE DIENTES'),
    ('COMBO B.D.C.P',60000,'BAÑO, DESLANADO, CORTE DE UÑAS Y PELUQUEADO')
    ;

SELECT * FROM servicio;
DROP TABLE servicio; 
TRUNCATE TABLE servicio;

CREATE TABLE IF NOT EXISTS detalles_servicio(
	id_detalles_servicio INT AUTO_INCREMENT NOT NULL,
	cedula VARCHAR(20) NOT NULL,
    id_servicio INT NOT NULL,
    hora_fecha_entrega DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_detalles_servicio),
    FOREIGN KEY (cedula) REFERENCES cliente(cedula),
    FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio)
);

SELECT * FROM detalles_servicio;
DROP TABLE detalles_servicio; 
TRUNCATE TABLE detalles_servicio;

INSERT INTO detalles_servicio(cedula, id_servicio)
VALUES
	('123456789',2)
    ;